# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Run backend tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test_backend:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 15.x ]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: testingdb
          MYSQL_ROOT_PASSWORD: magic
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install server-side dependencies and build
      run: |
        npm ci --prefix server/
        npm run build --if-present --prefix server/
    - name: Install MySQL CLI client
      run: |
        sudo apt-get update
        sudo apt-get install -y mysql-client
    - name: Verify that MySQL database is running
      run: |
        mysql --host 127.0.0.1 --port ${{ job.services.mysql.ports[3306] }} -u root -pmagic -e "SHOW DATABASES;"
    - name: Run server-side tests
      run: |
        sudo /etc/init.d/mysql start
        npm run test --prefix server/
      env:
        DATABASE_PORT: ${{ job.services.mysql.ports[3306] }}
        DATABASE_USERNAME: root
        DATABASE_NAME: db
        DATABASE_PASSWORD: magic
        DATABASE_HOST: 127.0.0.1
        TEST_DATABASE_NAME: testingdb
