name: Run frontend tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test_frontend:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install client-side dependencies and build
        run: |
          npm ci --prefix client/
          npm run build --if-present --prefix client/
      - name: Run client-side tests
        run: |
          npm run test --prefix client/
